export type ListingStatus = 'approved' | 'pending_review' | 'payment_pending' | 'rejected';
export type ListingTier = 'free' | 'fast';

export type ListedToken = {
  id: string;
  name: string;
  symbol: string;
  address: string;
  description: string;
  logo_url: string;
  website?: string;
  telegram?: string;
  twitter?: string;
  listed_at: string;
  promoted: boolean;
  votes_24h: number;
  votes_all_time: number;
  holders?: number;
  price_usd?: number;
  market_cap_usd?: number;
  liquidity_usd?: number;
  volume_24h_usd?: number;
  change_24h_percent?: number;
  chart_url?: string;
  category?: string;
  status?: ListingStatus;
  listing_tier?: ListingTier;
  payment_reference?: string | null;
  payment_amount_ton?: number | null;
  promotion_duration_days?: number | null;
};
